query{
  allProject{
    pid
    title
    language
    description
  }
}
------------------------------------------------------------------------
query($PID:Int){
  getProjById(pid:$PID){
    pid
    title
    language
    description
  }
}
-------
{
  "PID":2
}

------------------------------------------------------------------------